### ISSUE TITLE
Load schema and model definitions automatically(recursively) instead of manually

### ISSUE THREAD

**Issue by jay-jlm** [bkegley/graphql-server-starter#7]
Here's a gist on how I made this work:
https://gist.github.com/jay-jlm/b09075a22cb6571fc4265ca74ee0e3de

If you know a better way, let me know.

**Comment by bkegley** [comment]
I'm loving this @jay-jlm! So much better. I'm working on implementation but what would you think of the modules hierarchy like this: 
```
modules
  Cat
    model.js
    resolvers.js
    types.js
```
That would give us the feature-orientated hierarchy you mentioned in #6 but still keep the each concern separate. Resolvers can get lengthy.

I should have some time tonight to put into this.

**Comment by bkegley** [comment]
@jay-jlm I made some progress on implementing the changes. I had to modify your gist slightly for the directory hierarchy. You can check out the changes on the [load-modules branch](https://github.com/bkegley/graphql-server-starter/tree/load-modules).

Currently, it loads all modules automatically like you were pointing out. I'm a little concerned about how dependent the function is on file-naming conventions so I wrote a little CLI to automatically create new modules from .ejs templates. I'll push that tonight.

TODO:
parseModules only works if the modules are in the /modules directory. I'd like to be able to nest directories to better organized features. I got a start on it [this gist](https://gist.github.com/bkegley/40b0886b666f0d7e29c302a49e4b8d42) but wasn't able to get it functioning. If you'd like to look it over that'd be much appreciated.

**Comment by bkegley** [comment]
I'm happy where this is at now with 60725cd78e75f17e61e7891f84b6b60cae0dbfb7.

I'll merge this to master.

**Comment by jay-jlm** [comment]
Whoa, I was not honestly expecting this change to go thru. 
Thank you so much, it's looking great!
